// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.overlay.broadcastfec

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("overlay.broadcastFec.id")
@TLCombinatorId(0xFB3155A6)
public data class OverlayBroadcastFecId(
    @TLFixedSize(value = 32)
    @get:JvmName("src")
    public val src: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @TLFixedSize(value = 32)
    @get:JvmName("type")
    public val type: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("data_hash")
    @TLFixedSize(value = 32)
    @get:JvmName("dataHash")
    public val dataHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("size")
    public val size: Int,
    @get:JvmName("flags")
    public val flags: Int,
) {
    public companion object
}
