// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.overlay

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.ton.PublicKey
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface OverlayCertificate {
    @Serializable
    @SerialName("overlay.certificate")
    @TLCombinatorId(0xE09ED731)
    public data class Certificate(
        @SerialName("issued_by")
        @get:JvmName("issuedBy")
        public val issuedBy: PublicKey,
        @SerialName("expire_at")
        @get:JvmName("expireAt")
        public val expireAt: Int,
        @SerialName("max_size")
        @get:JvmName("maxSize")
        public val maxSize: Int,
        @get:JvmName("signature")
        public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : OverlayCertificate {
        public companion object
    }

    @Serializable
    @SerialName("overlay.certificateV2")
    @TLCombinatorId(0xB43F9C83)
    public data class CertificateV2(
        @SerialName("issued_by")
        @get:JvmName("issuedBy")
        public val issuedBy: PublicKey,
        @SerialName("expire_at")
        @get:JvmName("expireAt")
        public val expireAt: Int,
        @SerialName("max_size")
        @get:JvmName("maxSize")
        public val maxSize: Int,
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("signature")
        public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : OverlayCertificate {
        public companion object
    }

    @Serializable
    @SerialName("overlay.emptyCertificate")
    @TLCombinatorId(0x32DABCCF)
    public object EmptyCertificate : OverlayCertificate

    public companion object
}
