// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.overlay

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.PublicKey
import kotlin.jvm.JvmName

@Serializable
@SerialName("overlay.node")
@TLCombinatorId(0xB86B8A83)
public data class OverlayNode(
    @get:JvmName("id")
    public val id: PublicKey,
    @TLFixedSize(value = 32)
    @get:JvmName("overlay")
    public val overlay: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("version")
    public val version: Int,
    @get:JvmName("signature")
    public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
