// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.overlay

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("overlay.nodes")
@TLCombinatorId(0xE487290E)
public data class OverlayNodes(
    @get:JvmName("nodes")
    public val nodes: List<OverlayNode>,
) {
    public companion object
}
