// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.overlay

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.ton.PublicKey
import tl.ton.fec.FecType
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface OverlayBroadcast {
    @Serializable
    @SerialName("overlay.fec.received")
    @TLCombinatorId(0xD55C14EC)
    public data class FecReceived(
        @TLFixedSize(value = 32)
        @get:JvmName("hash")
        public val hash: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : OverlayBroadcast {
        public companion object
    }

    @Serializable
    @SerialName("overlay.fec.completed")
    @TLCombinatorId(0x09D76914)
    public data class FecCompleted(
        @TLFixedSize(value = 32)
        @get:JvmName("hash")
        public val hash: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : OverlayBroadcast {
        public companion object
    }

    @Serializable
    @SerialName("overlay.unicast")
    @TLCombinatorId(0x33534E24)
    public data class Unicast(
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : OverlayBroadcast {
        public companion object
    }

    @Serializable
    @SerialName("overlay.broadcast")
    @TLCombinatorId(0xB15A2B6B)
    public data class Broadcast(
        @get:JvmName("src")
        public val src: PublicKey,
        @get:JvmName("certificate")
        public val certificate: OverlayCertificate,
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("date")
        public val date: Int,
        @get:JvmName("signature")
        public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : OverlayBroadcast {
        public companion object
    }

    @Serializable
    @SerialName("overlay.broadcastFec")
    @TLCombinatorId(0xBAD7C36A)
    public data class BroadcastFec(
        @get:JvmName("src")
        public val src: PublicKey,
        @get:JvmName("certificate")
        public val certificate: OverlayCertificate,
        @SerialName("data_hash")
        @TLFixedSize(value = 32)
        @get:JvmName("dataHash")
        public val dataHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("data_size")
        @get:JvmName("dataSize")
        public val dataSize: Int,
        @get:JvmName("flags")
        public val flags: Int,
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("seqno")
        public val seqno: Int,
        @get:JvmName("fec")
        public val fec: FecType,
        @get:JvmName("date")
        public val date: Int,
        @get:JvmName("signature")
        public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : OverlayBroadcast {
        public companion object
    }

    @Serializable
    @SerialName("overlay.broadcastFecShort")
    @TLCombinatorId(0xF1881342)
    public data class BroadcastFecShort(
        @get:JvmName("src")
        public val src: PublicKey,
        @get:JvmName("certificate")
        public val certificate: OverlayCertificate,
        @SerialName("broadcast_hash")
        @TLFixedSize(value = 32)
        @get:JvmName("broadcastHash")
        public val broadcastHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("part_data_hash")
        @TLFixedSize(value = 32)
        @get:JvmName("partDataHash")
        public val partDataHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("seqno")
        public val seqno: Int,
        @get:JvmName("signature")
        public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : OverlayBroadcast {
        public companion object
    }

    @Serializable
    @SerialName("overlay.broadcastNotFound")
    @TLCombinatorId(0x95863624)
    public object BroadcastNotFound : OverlayBroadcast

    public companion object
}
