// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.overlay

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("overlay.getRandomPeers")
@TLCombinatorId(0x48ee64ab)
public data class OverlayGetRandomPeers(
    @get:JvmName("peers")
    public val peers: OverlayNodes,
) {
    public companion object
}
