// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.adnl.config

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.adnl.AdnlNodes

@Serializable
@SerialName("adnl.config.global")
@TLCombinatorId(0xBE6F80D0)
public data class AdnlConfigGlobal(
    @SerialName("static_nodes")
    @get:JvmName("staticNodes")
    public val staticNodes: AdnlNodes,
) {
    public companion object
}
