// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.dht.db

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.dht.DhtNodes

@Serializable
@SerialName("dht.db.bucket")
@TLCombinatorId(0xB39CFA6C)
public data class DhtDbBucket(
    @get:JvmName("nodes")
    public val nodes: DhtNodes,
) {
    public companion object
}
