// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.keyBlocks")
@TLCombinatorId(0x07664D59)
public data class TonNodeKeyBlocks(
    @get:JvmName("blocks")
    public val blocks: List<TonNodeBlockIdExt>,
    @get:JvmName("incomplete")
    public val incomplete: Boolean,
    @get:JvmName("error")
    public val error: Boolean,
) {
    public companion object
}
