// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.sessionId")
@TLCombinatorId(0x7A9236BA)
public data class TonNodeSessionId(
    @get:JvmName("workchain")
    public val workchain: Int,
    @get:JvmName("shard")
    public val shard: Long,
    @SerialName("cc_seqno")
    @get:JvmName("ccSeqno")
    public val ccSeqno: Int,
    @SerialName("opts_hash")
    @TLFixedSize(value = 32)
    @get:JvmName("optsHash")
    public val optsHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
