// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface TonNodeBlockDescription {
    @Serializable
    @SerialName("tonNode.blockDescriptionEmpty")
    @TLCombinatorId(0x8384AE95)
    public object BlockDescriptionEmpty : TonNodeBlockDescription

    @Serializable
    @SerialName("tonNode.blockDescription")
    @TLCombinatorId(0x46A1D088)
    public data class BlockDescription(
        @get:JvmName("id")
        public val id: TonNodeBlockIdExt,
    ) : TonNodeBlockDescription {
        public companion object
    }

    public companion object
}
