// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.downloadKeyBlockProofLink")
@TLCombinatorId(0x25A65CB5)
public data class TonNodeDownloadKeyBlockProofLink(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
) {
    public companion object
}
