// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.prepareBlock")
@TLCombinatorId(0x482D2B50)
public data class TonNodePrepareBlock(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
) {
    public companion object
}
