// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.downloadZeroState")
@TLCombinatorId(0x977D50B3)
public data class TonNodeDownloadZeroState(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
) {
    public companion object
}
