// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.getNextKeyBlockIds")
@TLCombinatorId(0xF544E675)
public data class TonNodeGetNextKeyBlockIds(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
    @SerialName("max_size")
    @get:JvmName("maxSize")
    public val maxSize: Int,
) {
    public companion object
}
