// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.getArchiveInfo")
@TLCombinatorId(0xC3E54FC2)
public data class TonNodeGetArchiveInfo(
    @SerialName("masterchain_seqno")
    @get:JvmName("masterchainSeqno")
    public val masterchainSeqno: Int,
) {
    public companion object
}
