// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.getArchiveSlice")
@TLCombinatorId(0xCBF93E0D)
public data class TonNodeGetArchiveSlice(
    @SerialName("archive_id")
    @get:JvmName("archiveId")
    public val archiveId: Long,
    @get:JvmName("offset")
    public val offset: Long,
    @SerialName("max_size")
    @get:JvmName("maxSize")
    public val maxSize: Int,
) {
    public companion object
}
