// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface TonNodeDataFull {
    @Serializable
    @SerialName("tonNode.dataFull")
    @TLCombinatorId(0xBE589F93)
    public data class DataFull(
        @get:JvmName("id")
        public val id: TonNodeBlockIdExt,
        @get:JvmName("proof")
        public val proof: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("block")
        public val block: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("is_link")
        @get:JvmName("isLink")
        public val isLink: Boolean,
    ) : TonNodeDataFull {
        public companion object
    }

    @Serializable
    @SerialName("tonNode.dataFullEmpty")
    @TLCombinatorId(0x576E85CA)
    public object DataFullEmpty : TonNodeDataFull

    public companion object
}
