// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.blocksDescription")
@TLCombinatorId(0xD62A612C)
public data class TonNodeBlocksDescription(
    @get:JvmName("ids")
    public val ids: List<TonNodeBlockIdExt>,
    @get:JvmName("incomplete")
    public val incomplete: Boolean,
) {
    public companion object
}
