// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.dataList")
@TLCombinatorId(0x14F43313)
public data class TonNodeDataList(
    @get:JvmName("data")
    public val `data`: List<@Serializable(Base64ByteStringSerializer::class) ByteString>,
) {
    public companion object
}
