// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.getNextBlockDescription")
@TLCombinatorId(0x22E78BC8)
public data class TonNodeGetNextBlockDescription(
    @SerialName("prev_block")
    @get:JvmName("prevBlock")
    public val prevBlock: TonNodeBlockIdExt,
) {
    public companion object
}
