// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class TonNodePrepared {
    @SerialName("tonNode.prepared")
    @TLCombinatorId(0xEAC4BBCD)
    PREPARED,

    @SerialName("tonNode.notFound")
    @TLCombinatorId(0xE2C33DA6)
    NOT_FOUND,
    ;

    public companion object
}
