// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.capabilities")
@TLCombinatorId(0xF5BF60C0)
public data class TonNodeCapabilities(
    @get:JvmName("version")
    public val version: Int,
    @get:JvmName("capabilities")
    public val capabilities: Long,
) {
    public companion object
}
