// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.tonnode

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.getNextBlocksDescription")
@TLCombinatorId(0x7D34CF5D)
public data class TonNodeGetNextBlocksDescription(
    @SerialName("prev_block")
    @get:JvmName("prevBlock")
    public val prevBlock: TonNodeBlockIdExt,
    @get:JvmName("limit")
    public val limit: Int,
) {
    public companion object
}
