// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("adnl.tunnelPacketContents")
@TLCombinatorId(0xC59138B4)
public data class AdnlTunnelPacketContents(
    @get:JvmName("rand1")
    public val rand1: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("flags")
    public val flags: Int,
    @SerialName("from_ip")
    @TLConditional("flags", 0)
    @get:JvmName("fromIp")
    public val fromIp: Int? = null,
    @SerialName("from_port")
    @TLConditional("flags", 0)
    @get:JvmName("fromPort")
    public val fromPort: Int? = null,
    @TLConditional("flags", 1)
    @get:JvmName("message")
    public val message: @Serializable(Base64ByteStringSerializer::class) ByteString? = null,
    @TLConditional("flags", 2)
    @get:JvmName("statistics")
    public val statistics: @Serializable(Base64ByteStringSerializer::class) ByteString? = null,
    @TLConditional("flags", 3)
    @get:JvmName("payment")
    public val payment: @Serializable(Base64ByteStringSerializer::class) ByteString? = null,
    @get:JvmName("rand2")
    public val rand2: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
