// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("adnl.proxyToFast")
@TLCombinatorId(0xB4EE21D6)
public data class AdnlProxyToSign(
    @get:JvmName("ip")
    public val ip: Int,
    @get:JvmName("port")
    public val port: Int,
    @get:JvmName("date")
    public val date: Int,
    @TLFixedSize(value = 32)
    @get:JvmName("signature")
    public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
