// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface AdnlAddress {
    @Serializable
    @SerialName("adnl.address.udp")
    @TLCombinatorId(0x670DA6E7)
    public data class Udp(
        @get:JvmName("ip")
        public val ip: Int,
        @get:JvmName("port")
        public val port: Int,
    ) : AdnlAddress {
        public companion object
    }

    @Serializable
    @SerialName("adnl.address.udp6")
    @TLCombinatorId(0xE31D63FA)
    public data class Udp6(
        @TLFixedSize(value = 16)
        @get:JvmName("ip")
        public val ip: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("port")
        public val port: Int,
    ) : AdnlAddress {
        public companion object
    }

    @Serializable
    @SerialName("adnl.address.tunnel")
    @TLCombinatorId(0x092B02EB)
    public data class Tunnel(
        @TLFixedSize(value = 32)
        @get:JvmName("to")
        public val to: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("pubkey")
        public val pubkey: PublicKey,
    ) : AdnlAddress {
        public companion object
    }

    @Serializable
    @SerialName("adnl.address.reverse")
    @TLCombinatorId(0x27795286)
    public object Reverse : AdnlAddress

    public companion object
}
