// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("adnl.packetContents")
@TLCombinatorId(0xD142CD89)
public data class AdnlPacketContents(
    @get:JvmName("rand1")
    public val rand1: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("from")
    public val from: PublicKey? = null,
    @SerialName("from_short")
    @TLConditional("flags", 1)
    @get:JvmName("fromShort")
    public val fromShort: AdnlIdShort? = null,
    @TLConditional("flags", 2)
    @get:JvmName("message")
    public val message: AdnlMessage? = null,
    @TLConditional("flags", 3)
    @get:JvmName("messages")
    public val messages: List<AdnlMessage>? = null,
    @TLConditional("flags", 4)
    @get:JvmName("address")
    public val address: AdnlAddressList? = null,
    @SerialName("priority_address")
    @TLConditional("flags", 5)
    @get:JvmName("priorityAddress")
    public val priorityAddress: AdnlAddressList? = null,
    @TLConditional("flags", 6)
    @get:JvmName("seqno")
    public val seqno: Long? = null,
    @SerialName("confirm_seqno")
    @TLConditional("flags", 7)
    @get:JvmName("confirmSeqno")
    public val confirmSeqno: Long? = null,
    @SerialName("recv_addr_list_version")
    @TLConditional("flags", 8)
    @get:JvmName("recvAddrListVersion")
    public val recvAddrListVersion: Int? = null,
    @SerialName("recv_priority_addr_list_version")
    @TLConditional("flags", 9)
    @get:JvmName("recvPriorityAddrListVersion")
    public val recvPriorityAddrListVersion: Int? = null,
    @SerialName("reinit_date")
    @TLConditional("flags", 10)
    @get:JvmName("reinitDate")
    public val reinitDate: Int? = null,
    @SerialName("dst_reinit_date")
    @TLConditional("flags", 10)
    @get:JvmName("dstReinitDate")
    public val dstReinitDate: Int? = null,
    @TLConditional("flags", 11)
    @get:JvmName("signature")
    public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString? = null,
    @get:JvmName("rand2")
    public val rand2: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
