// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("adnl.pong")
@TLCombinatorId(0x20747C0E)
public data class AdnlPong(
    @get:JvmName("value")
    public val `value`: Long,
) {
    public companion object
}
