// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface AdnlProxyControlPacket {
    @Serializable
    @SerialName("adnl.proxyControlPacketPing")
    @TLCombinatorId(0x3796E44B)
    public data class ProxyControlPacketPing(
        @TLFixedSize(value = 32)
        @get:JvmName("id")
        public val id: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : AdnlProxyControlPacket {
        public companion object
    }

    @Serializable
    @SerialName("adnl.proxyControlPacketPong")
    @TLCombinatorId(0x4BD1DBFC)
    public data class ProxyControlPacketPong(
        @TLFixedSize(value = 32)
        @get:JvmName("id")
        public val id: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : AdnlProxyControlPacket {
        public companion object
    }

    @Serializable
    @SerialName("adnl.proxyControlPacketRegister")
    @TLCombinatorId(0xC309B23F)
    public data class ProxyControlPacketRegister(
        @get:JvmName("ip")
        public val ip: Int,
        @get:JvmName("port")
        public val port: Int,
    ) : AdnlProxyControlPacket {
        public companion object
    }

    public companion object
}
