// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("dht.pong")
@TLCombinatorId(0x5A8AEF81)
public data class DhtPong(
    @SerialName("random_id")
    @get:JvmName("randomId")
    public val randomId: Long,
) {
    public companion object
}
