// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface DhtReversePingResult {
    @Serializable
    @SerialName("dht.clientNotFound")
    @TLCombinatorId(0x2D1C7E6F)
    public data class ClientNotFound(
        @get:JvmName("nodes")
        public val nodes: DhtNodes,
    ) : DhtReversePingResult {
        public companion object
    }

    @Serializable
    @SerialName("dht.reversePingOk")
    @TLCombinatorId(0x204030A2)
    public object ReversePingOk : DhtReversePingResult

    public companion object
}
