// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("dht.registerReverseConnection")
@TLCombinatorId(0xE6149BD8)
public data class DhtRegisterReverseConnection(
    @get:JvmName("node")
    public val node: PublicKey,
    @get:JvmName("ttl")
    public val ttl: Int,
    @get:JvmName("signature")
    public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
