// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class DhtUpdateRule {
    @SerialName("dht.updateRule.signature")
    @TLCombinatorId(0xCC9F31F7)
    SIGNATURE,
    @SerialName("dht.updateRule.anybody")
    @TLCombinatorId(0x61578E14)
    ANYBODY,
    @SerialName("dht.updateRule.overlayNodes")
    @TLCombinatorId(0x26779383)
    OVERLAY_NODES,
    ;

    public companion object
}
