// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("overlay.node.toSign")
@TLCombinatorId(0x03D8A8E1)
public data class OverlayNodeToSign(
    @get:JvmName("id")
    public val id: AdnlIdShort,
    @TLFixedSize(value = 32)
    @get:JvmName("overlay")
    public val overlay: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("version")
    public val version: Int,
) {
    public companion object
}
