// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface OverlayCertificateId {
    @Serializable
    @SerialName("overlay.certificateId")
    @TLCombinatorId(0x8FAE60B9)
    public data class CertificateId(
        @SerialName("overlay_id")
        @TLFixedSize(value = 32)
        @get:JvmName("overlayId")
        public val overlayId: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @TLFixedSize(value = 32)
        @get:JvmName("node")
        public val node: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("expire_at")
        @get:JvmName("expireAt")
        public val expireAt: Int,
        @SerialName("max_size")
        @get:JvmName("maxSize")
        public val maxSize: Int,
    ) : OverlayCertificateId {
        public companion object
    }

    @Serializable
    @SerialName("overlay.certificateIdV2")
    @TLCombinatorId(0xFC6CD2A7)
    public data class CertificateIdV2(
        @SerialName("overlay_id")
        @TLFixedSize(value = 32)
        @get:JvmName("overlayId")
        public val overlayId: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @TLFixedSize(value = 32)
        @get:JvmName("node")
        public val node: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("expire_at")
        @get:JvmName("expireAt")
        public val expireAt: Int,
        @SerialName("max_size")
        @get:JvmName("maxSize")
        public val maxSize: Int,
        @get:JvmName("flags")
        public val flags: Int,
    ) : OverlayCertificateId {
        public companion object
    }

    public companion object
}
