// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("overlay.db.nodes")
@TLCombinatorId(0xD588CE1A)
public data class OverlayDbNodes(
    @get:JvmName("nodes")
    public val nodes: OverlayNodes,
) {
    public companion object
}
