// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface PublicKey {
    @Serializable
    @SerialName("pub.unenc")
    @TLCombinatorId(0xB61F450A)
    public data class Unenc(
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : PublicKey {
        public companion object
    }

    @Serializable
    @SerialName("pub.ed25519")
    @TLCombinatorId(0x4813B4C6)
    public data class Ed25519(
        @TLFixedSize(value = 32)
        @get:JvmName("key")
        public val key: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : PublicKey {
        public companion object
    }

    @Serializable
    @SerialName("pub.aes")
    @TLCombinatorId(0x2DBCADD4)
    public data class Aes(
        @TLFixedSize(value = 32)
        @get:JvmName("key")
        public val key: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : PublicKey {
        public companion object
    }

    @Serializable
    @SerialName("pub.overlay")
    @TLCombinatorId(0x34BA45CB)
    public data class Overlay(
        @get:JvmName("name")
        public val name: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : PublicKey {
        public companion object
    }

    public companion object
}
