// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface Rldp2MessagePart {
    @Serializable
    @SerialName("rldp2.messagePart")
    @TLCombinatorId(0x11480B6E)
    public data class MessagePart(
        @SerialName("transfer_id")
        @TLFixedSize(value = 32)
        @get:JvmName("transferId")
        public val transferId: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("fec_type")
        @get:JvmName("fecType")
        public val fecType: FecType,
        @get:JvmName("part")
        public val part: Int,
        @SerialName("total_size")
        @get:JvmName("totalSize")
        public val totalSize: Long,
        @get:JvmName("seqno")
        public val seqno: Int,
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : Rldp2MessagePart {
        public companion object
    }

    @Serializable
    @SerialName("rldp2.confirm")
    @TLCombinatorId(0x23E69945)
    public data class Confirm(
        @SerialName("transfer_id")
        @TLFixedSize(value = 32)
        @get:JvmName("transferId")
        public val transferId: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("part")
        public val part: Int,
        @SerialName("max_seqno")
        @get:JvmName("maxSeqno")
        public val maxSeqno: Int,
        @SerialName("received_mask")
        @get:JvmName("receivedMask")
        public val receivedMask: Int,
        @SerialName("received_count")
        @get:JvmName("receivedCount")
        public val receivedCount: Int,
    ) : Rldp2MessagePart {
        public companion object
    }

    @Serializable
    @SerialName("rldp2.complete")
    @TLCombinatorId(0x36B9081F)
    public data class Complete(
        @SerialName("transfer_id")
        @TLFixedSize(value = 32)
        @get:JvmName("transferId")
        public val transferId: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("part")
        public val part: Int,
    ) : Rldp2MessagePart {
        public companion object
    }

    public companion object
}
