// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.downloadNextBlockFull")
@TLCombinatorId(0x1C55A186)
public data class TonNodeDownloadNextBlockFull(
    @SerialName("prev_block")
    @get:JvmName("prevBlock")
    public val prevBlock: TonNodeBlockIdExt,
) {
    public companion object
}
