// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class TonNodePreparedProof {
    @SerialName("tonNode.preparedProofEmpty")
    @TLCombinatorId(0xC769C17A)
    PREPARED_PROOF_EMPTY,

    @SerialName("tonNode.preparedProof")
    @TLCombinatorId(0x899F9A4B)
    PREPARED_PROOF,

    @SerialName("tonNode.preparedProofLink")
    @TLCombinatorId(0x3DFF328D)
    PREPARED_PROOF_LINK,
    ;

    public companion object
}
