// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.downloadBlockProofLink")
@TLCombinatorId(0x5B93D662)
public data class TonNodeDownloadBlockProofLink(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
) {
    public companion object
}
