// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.zeroStateIdExt")
@TLCombinatorId(0x1D7235AE)
public data class TonNodeZeroStateIdExt(
    @get:JvmName("workchain")
    public val workchain: Int,
    @SerialName("root_hash")
    @TLFixedSize(value = 32)
    @get:JvmName("rootHash")
    public val rootHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @SerialName("file_hash")
    @TLFixedSize(value = 32)
    @get:JvmName("fileHash")
    public val fileHash: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
