// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.prepareKeyBlockProof")
@TLCombinatorId(0x2540ED64)
public data class TonNodePrepareKeyBlockProof(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
    @SerialName("allow_partial")
    @get:JvmName("allowPartial")
    public val allowPartial: Boolean,
) {
    public companion object
}
