// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.prepareBlockProof")
@TLCombinatorId(0x7CAEFE01)
public data class TonNodePrepareBlockProof(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
    @SerialName("allow_partial")
    @get:JvmName("allowPartial")
    public val allowPartial: Boolean,
) {
    public companion object
}
