// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.downloadBlock")
@TLCombinatorId(0xFC3FB100)
public data class TonNodeDownloadBlock(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
) {
    public companion object
}
