// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public enum class TonNodePreparedState {
    @SerialName("tonNode.preparedState")
    @TLCombinatorId(0x375BCB6D)
    PREPARED_STATE,

    @SerialName("tonNode.notFoundState")
    @TLCombinatorId(0x32390A51)
    NOT_FOUND_STATE,
    ;

    public companion object
}
