// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.downloadPersistentStateSlice")
@TLCombinatorId(0x9D8F860E)
public data class TonNodeDownloadPersistentStateSlice(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
    @SerialName("masterchain_block")
    @get:JvmName("masterchainBlock")
    public val masterchainBlock: TonNodeBlockIdExt,
    @get:JvmName("offset")
    public val offset: Long,
    @SerialName("max_size")
    @get:JvmName("maxSize")
    public val maxSize: Long,
) {
    public companion object
}
