// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("tonNode.newShardBlock")
@TLCombinatorId(0xA49DC229)
public data class TonNodeNewShardBlock(
    @get:JvmName("block")
    public val block: TonNodeBlockIdExt,
    @SerialName("cc_seqno")
    @get:JvmName("ccSeqno")
    public val ccSeqno: Int,
    @get:JvmName("data")
    public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
