// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.dht

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("dht.key")
@TLCombinatorId(0xF667DE8F)
public data class DhtKey(
    @TLFixedSize(value = 32)
    @get:JvmName("id")
    public val id: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("name")
    public val name: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("idx")
    public val idx: Int,
) {
    public companion object
}
