// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.dht

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.PublicKey

@Serializable
@SerialName("dht.keyDescription")
@TLCombinatorId(0x281D4E05)
public data class DhtKeyDescription(
    @get:JvmName("key")
    public val key: DhtKey,
    @get:JvmName("id")
    public val id: PublicKey,
    @SerialName("update_rule")
    @get:JvmName("updateRule")
    public val updateRule: DhtUpdateRule,
    @get:JvmName("signature")
    public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
