// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.dht

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("dht.nodes")
@TLCombinatorId(0x7974A0BE)
public data class DhtNodes(
    @get:JvmName("nodes")
    public val nodes: List<DhtNode>,
) {
    public companion object
}
