// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.dht

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.PublicKey
import tl.ton.adnl.AdnlAddressList

@Serializable
@SerialName("dht.node")
@TLCombinatorId(0x84533248)
public data class DhtNode(
    @get:JvmName("id")
    public val id: PublicKey,
    @SerialName("addr_list")
    @get:JvmName("addrList")
    public val addrList: AdnlAddressList,
    @get:JvmName("version")
    public val version: Int,
    @get:JvmName("signature")
    public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
