// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.dht

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("dht.value")
@TLCombinatorId(0x90AD27CB)
public data class DhtValue(
    @get:JvmName("key")
    public val key: DhtKeyDescription,
    @get:JvmName("value")
    public val `value`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("ttl")
    public val ttl: Int,
    @get:JvmName("signature")
    public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
