// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.adnl.id

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("adnl.id.short")
@TLCombinatorId(0x3E3F654F)
public data class AdnlIdShort(
    @TLFixedSize(value = 32)
    @get:JvmName("id")
    public val id: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
