// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.rldp

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface RldpMessage {
    @Serializable
    @SerialName("rldp.message")
    @TLCombinatorId(0x7D1BCD1E)
    public data class Message(
        @TLFixedSize(value = 32)
        @get:JvmName("id")
        public val id: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : RldpMessage {
        public companion object
    }

    @Serializable
    @SerialName("rldp.query")
    @TLCombinatorId(0x8A794D69)
    public data class Query(
        @SerialName("query_id")
        @TLFixedSize(value = 32)
        @get:JvmName("queryId")
        public val queryId: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("max_answer_size")
        @get:JvmName("maxAnswerSize")
        public val maxAnswerSize: Long,
        @get:JvmName("timeout")
        public val timeout: Int,
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : RldpMessage {
        public companion object
    }

    @Serializable
    @SerialName("rldp.answer")
    @TLCombinatorId(0xA3FC5C03)
    public data class Answer(
        @SerialName("query_id")
        @TLFixedSize(value = 32)
        @get:JvmName("queryId")
        public val queryId: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : RldpMessage {
        public companion object
    }

    public companion object
}
