// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.overlay.db

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlin.jvm.JvmName

@Serializable
@SerialName("overlay.db.key.nodes")
@TLCombinatorId(0xC4D07316)
public data class OverlayDbKey(
    @SerialName("local_id")
    @TLFixedSize(value = 32)
    @get:JvmName("localId")
    public val localId: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @TLFixedSize(value = 32)
    @get:JvmName("overlay")
    public val overlay: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
