// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.fec

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import kotlin.jvm.JvmName

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface FecType {
    @Serializable
    @SerialName("fec.raptorQ")
    @TLCombinatorId(0x8B93A7E0)
    public data class RaptorQ(
        @SerialName("data_size")
        @get:JvmName("dataSize")
        public val dataSize: Int,
        @SerialName("symbol_size")
        @get:JvmName("symbolSize")
        public val symbolSize: Int,
        @SerialName("symbols_count")
        @get:JvmName("symbolsCount")
        public val symbolsCount: Int,
    ) : FecType {
        public companion object
    }

    @Serializable
    @SerialName("fec.roundRobin")
    @TLCombinatorId(0x32F528E4)
    public data class RoundRobin(
        @SerialName("data_size")
        @get:JvmName("dataSize")
        public val dataSize: Int,
        @SerialName("symbol_size")
        @get:JvmName("symbolSize")
        public val symbolSize: Int,
        @SerialName("symbols_count")
        @get:JvmName("symbolsCount")
        public val symbolsCount: Int,
    ) : FecType {
        public companion object
    }

    @Serializable
    @SerialName("fec.online")
    @TLCombinatorId(0x0127660C)
    public data class Online(
        @SerialName("data_size")
        @get:JvmName("dataSize")
        public val dataSize: Int,
        @SerialName("symbol_size")
        @get:JvmName("symbolSize")
        public val symbolSize: Int,
        @SerialName("symbols_count")
        @get:JvmName("symbolsCount")
        public val symbolsCount: Int,
    ) : FecType {
        public companion object
    }

    public companion object
}
