// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.adnl

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface AdnlMessage {
    @Serializable
    @SerialName("adnl.message.createChannel")
    @TLCombinatorId(0xE673C3BB)
    public data class CreateChannel(
        @TLFixedSize(value = 32)
        @get:JvmName("key")
        public val key: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("date")
        public val date: Int,
    ) : AdnlMessage {
        public companion object
    }

    @Serializable
    @SerialName("adnl.message.confirmChannel")
    @TLCombinatorId(0x60DD1D69)
    public data class ConfirmChannel(
        @TLFixedSize(value = 32)
        @get:JvmName("key")
        public val key: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("peer_key")
        @TLFixedSize(value = 32)
        @get:JvmName("peerKey")
        public val peerKey: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("date")
        public val date: Int,
    ) : AdnlMessage {
        public companion object
    }

    @Serializable
    @SerialName("adnl.message.custom")
    @TLCombinatorId(0x204818F5)
    public data class Custom(
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : AdnlMessage {
        public companion object
    }

    @Serializable
    @SerialName("adnl.message.nop")
    @TLCombinatorId(0x17F8DFDA)
    public object Nop : AdnlMessage

    @Serializable
    @SerialName("adnl.message.reinit")
    @TLCombinatorId(0x10C20520)
    public data class Reinit(
        @get:JvmName("date")
        public val date: Int,
    ) : AdnlMessage {
        public companion object
    }

    @Serializable
    @SerialName("adnl.message.query")
    @TLCombinatorId(0xB48BF97A)
    public data class Query(
        @SerialName("query_id")
        @TLFixedSize(value = 32)
        @get:JvmName("queryId")
        public val queryId: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("query")
        public val query: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : AdnlMessage {
        public companion object
    }

    @Serializable
    @SerialName("adnl.message.answer")
    @TLCombinatorId(0x0FAC8416)
    public data class Answer(
        @SerialName("query_id")
        @TLFixedSize(value = 32)
        @get:JvmName("queryId")
        public val queryId: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @get:JvmName("answer")
        public val answer: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : AdnlMessage {
        public companion object
    }

    @Serializable
    @SerialName("adnl.message.part")
    @TLCombinatorId(0xFD452D39)
    public data class Part(
        @TLFixedSize(value = 32)
        @get:JvmName("hash")
        public val hash: @Serializable(Base64ByteStringSerializer::class) ByteString,
        @SerialName("total_size")
        @get:JvmName("totalSize")
        public val totalSize: Int,
        @get:JvmName("offset")
        public val offset: Int,
        @get:JvmName("data")
        public val `data`: @Serializable(Base64ByteStringSerializer::class) ByteString,
    ) : AdnlMessage {
        public companion object
    }

    public companion object
}
