// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.adnl

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("adnl.addressList")
@TLCombinatorId(0x2227E658)
public data class AdnlAddressList(
    @get:JvmName("addrs")
    public val addrs: List<AdnlAddress>,
    @get:JvmName("version")
    public val version: Int,
    @SerialName("reinit_date")
    @get:JvmName("reinitDate")
    public val reinitDate: Int,
    @get:JvmName("priority")
    public val priority: Int,
    @SerialName("expire_at")
    @get:JvmName("expireAt")
    public val expireAt: Int,
) {
    public companion object
}
