// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.adnl

import io.github.andreypfau.tl.serialization.Base64ByteStringSerializer
import io.github.andreypfau.tl.serialization.TLCombinatorId
import io.github.andreypfau.tl.serialization.TLConditional
import io.github.andreypfau.tl.serialization.TLFixedSize
import kotlin.jvm.JvmName
import kotlinx.io.bytestring.ByteString
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("adnl.proxyPacketHeader")
@TLCombinatorId(0x08693C78)
public data class AdnlProxyPacketHeader(
    @SerialName("proxy_id")
    @TLFixedSize(value = 32)
    @get:JvmName("proxyId")
    public val proxyId: @Serializable(Base64ByteStringSerializer::class) ByteString,
    @get:JvmName("flags")
    public val flags: Int,
    @TLConditional("flags", 0)
    @get:JvmName("ip")
    public val ip: Int? = null,
    @TLConditional("flags", 0)
    @get:JvmName("port")
    public val port: Int? = null,
    @SerialName("adnl_start_time")
    @TLConditional("flags", 1)
    @get:JvmName("adnlStartTime")
    public val adnlStartTime: Int? = null,
    @TLConditional("flags", 2)
    @get:JvmName("seqno")
    public val seqno: Long? = null,
    @TLConditional("flags", 3)
    @get:JvmName("date")
    public val date: Int? = null,
    @TLFixedSize(value = 32)
    @get:JvmName("signature")
    public val signature: @Serializable(Base64ByteStringSerializer::class) ByteString,
) {
    public companion object
}
