// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.adnl

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import tl.ton.PublicKey

@Serializable
@SerialName("adnl.node")
@TLCombinatorId(0x6B561285)
public data class AdnlNode(
    @get:JvmName("id")
    public val id: PublicKey,
    @SerialName("addr_list")
    @get:JvmName("addrList")
    public val addrList: AdnlAddressList,
) {
    public companion object
}
