// This file is generated by TLGenerator.kt
// Do not edit manually!
package tl.ton.dht.config

import io.github.andreypfau.tl.serialization.TLCombinatorId
import kotlin.jvm.JvmName
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonClassDiscriminator
import tl.ton.dht.DhtNodes

@Serializable
@JsonClassDiscriminator("@type")
public sealed interface DhtConfigGlobal {
    @Serializable
    @SerialName("dht.config.global")
    @TLCombinatorId(0x84CECA07)
    public data class Global(
        @SerialName("static_nodes")
        @get:JvmName("staticNodes")
        public val staticNodes: DhtNodes,
        @get:JvmName("k")
        public val k: Int,
        @get:JvmName("a")
        public val a: Int,
    ) : DhtConfigGlobal {
        public companion object
    }

    @Serializable
    @SerialName("dht.config.global_v2")
    @TLCombinatorId(0x69638427)
    public data class GlobalV2(
        @SerialName("static_nodes")
        @get:JvmName("staticNodes")
        public val staticNodes: DhtNodes,
        @get:JvmName("k")
        public val k: Int,
        @get:JvmName("a")
        public val a: Int,
        @SerialName("network_id")
        @get:JvmName("networkId")
        public val networkId: Int,
    ) : DhtConfigGlobal {
        public companion object
    }

    public companion object
}
